### PR TITLE
Erase tmp files as they are output to save space

### PR DESCRIPTION
**Pull request by glennhickey**
I'm running into some disk space issues with preprocessing.  For example, I estimate that the file from #37 will need about 600 gigs just to store the output.  This is a small change to try to keep that 600G from doubling to 1.2T by deleting fragments as they get merged into the final output.

### CODE REVIEW

**Comment by glennhickey** [comment]
Hmm, as I'm fixing bugs in and around `cactus_covered_intervals`, I don't think I can run it on one file after all.  First, the merged file won't be sorted, and second even when I sort it I get `chr1 1000769 1000965 is behind the sliding window (window start = 99509921)`.

**Comment by glennhickey** [comment]
@gsneha26 Just to confirm, since I seem to have gotten it confused before:  Do we expect running `cactus_covered_intervals` with `M = half what it was before`  separately on each file in `output_$RANDOM/tmp*.segments` and cat-ing the results to approximate the chunking/fragmenting original logic?   

This is what's now implemented in https://github.com/ComparativeGenomicsToolkit/cactus/pull/302, and I will repeat my comparison on human tomorrow.

**Comment by gsneha26** [comment]
Exactly, that is the expectation. CPU repeat-mask runs `cactus_covered_intervals` on the segment file for each query chunk separately. To approximate this logic -  GPU repeat-mask should run `cactus_covered_intervals` on each file in `output_$RANDOM/tmp*.segments`.

**Comment by gsneha26** [comment]
Also, what is the disk space that would be provided to the CPU repeat-mask?

**Comment by glennhickey** [comment]
Great, thanks.  The results doing this [are closer to the gpu](https://github.com/ComparativeGenomicsToolkit/cactus/pull/302#issuecomment-682099462).  Pretty crazy that doing it all at once wasn't more different.   Could you still merge this in if possible?  It's minor but will help keep our repos in sync, and avoids an unnecessary `cat` of all the files.

**Comment by glennhickey** [comment]
I never CPU masked that particular file, and am not sure what Joel used.  I imagine it could do it in less space as it doesn't need to store all the intervals at once (I think).  I am not really worried about disk anymore with the latest cactus changes.

**Comment by gsneha26** [comment]
I have made some changes in the latest commit which might help. I have added an option `--postprocess_cmd` where you can provide `cactus_covered_intervals M=34` so that it is run right after the sort command so that the post-processing is completed in parallel with segalign.

**Pull request closed without merging**
